bash -lc cat > /mnt/data/create_ai_llm_deck.js <<'EOF'
const pptxgen = require('pptxgenjs');
const { imageSizingCrop, imageSizingContain } = require('/home/oai/skills/slides/pptxgenjs_helpers/image');
const { warnIfSlideHasOverlaps, warnIfSlideElementsOutOfBounds } = require('/home/oai/skills/slides/pptxgenjs_helpers/layout');

const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'OpenAI';
pptx.subject = 'Teaching material about AI, LLMs, Generative AI, RAG, CAG, MCP, prompt engineering, and agent skills';
pptx.title = 'AI and Large Language Models';
pptx.company = 'OpenAI';
pptx.lang = 'en-US';
pptx.theme = {
  headFontFace: 'Aptos Display',
  bodyFontFace: 'Aptos',
  lang: 'en-US'
};
pptx.defineLayout({ name:'CUSTOM_WIDE', width:13.333, height:7.5 });
pptx.layout = 'CUSTOM_WIDE';

const W=13.333, H=7.5;
const C = { navy:'14213D', blue:'2563EB', cyan:'06B6D4', purple:'7C3AED', pink:'DB2777', orange:'F59E0B', green:'10B981', yellow:'FDE68A', red:'EF4444', slate:'334155', gray:'64748B', light:'F8FAFC', white:'FFFFFF', black:'0F172A', pale:'E0F2FE' };
const imgs = {
  classroom:'/mnt/data/a_bright_modern_classroom_learning_space_scene_in_batch_1.png',
  genai:'/mnt/data/a_wide_clean_colorful_infographic_concept_illu_batch_2.png',
  rag:'/mnt/data/a_clean_high_quality_3d_cgi_illustration_with_a_s_batch_3.png',
  agents:'/mnt/data/wide_clean_3d_illustration_style_scene_in_a_softl_batch_4.png',
};
function addBg(slide, color=C.light){ slide.background = { color }; }
function title(slide, t, sub){ slide.addText(t,{x:0.55,y:0.35,w:7.5,h:0.5,fontFace:'Aptos Display',fontSize:30,bold:true,color:C.black,margin:0}); if(sub) slide.addText(sub,{x:0.58,y:0.88,w:9.2,h:0.38,fontSize:13,color:C.gray,margin:0}); }
function pill(slide, txt, x,y,w, color=C.blue){ slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h:0.38,rectRadius:0.08,fill:{color,transparency:5},line:{color,transparency:100}}); slide.addText(txt,{x:x+0.1,y:y+0.095,w:w-0.2,h:0.16,fontSize:8.5,bold:true,color:C.white,align:'center',margin:0}); }
function card(slide, x,y,w,h,opts={}){ slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.12,fill:{color:opts.fill||C.white,transparency:opts.transparency||0},line:{color:opts.line||'E2E8F0',transparency:opts.lineTrans||0,pt:1}}); }
function bigNum(slide,n,x,y,color){ slide.addText(String(n),{x,y,w:0.65,h:0.5,fontSize:30,bold:true,color,margin:0}); }
function bullet(slide, lines, x,y,w,h,opts={}){ slide.addText(lines.map(s=>'• '+s).join('\n'),{x,y,w,h,fontSize:opts.size||17,color:opts.color||C.slate,breakLine:false,fit:'shrink',margin:0.05,bullet:null,paraSpaceAfterPt:5}); }
function connector(slide,x1,y1,x2,y2,color=C.blue){ slide.addShape(pptx.ShapeType.line,{x:x1,y:y1,w:x2-x1,h:y2-y1,line:{color,pt:2,beginArrowType:'none',endArrowType:'triangle'}}); }
function footer(slide, num){ slide.addText(`AI & LLMs for High School • ${num}`,{x:9.9,y:7.12,w:2.8,h:0.18,fontSize:8,color:'94A3B8',align:'right',margin:0}); }
function notes(slide, txt){ slide.addNotes(txt); }
function imgCrop(slide,path,x,y,w,h,cx,cy,cw,ch){ slide.addImage({path,...imageSizingCrop(path,x,y,w,h,cx,cy,cw,ch)}); }
function imgContain(slide,path,x,y,w,h){ slide.addImage({path,...imageSizingContain(path,x,y,w,h)}); }

let s, n=1;
// 1
s=pptx.addSlide(); addBg(s,C.navy); imgCrop(s,imgs.classroom,0,0,W,H); s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:H,fill:{color:'000000',transparency:38},line:{transparency:100}}); s.addText('AI & Large Language Models',{x:0.75,y:0.8,w:8.0,h:0.7,fontFace:'Aptos Display',fontSize:42,bold:true,color:C.white,margin:0}); s.addText('A visual teaching deck for high school students',{x:0.8,y:1.65,w:7.5,h:0.34,fontSize:20,color:'DBEAFE',margin:0}); pill(s,'Generative AI',0.8,2.25,1.55,C.purple); pill(s,'LLMs',2.55,2.25,0.95,C.blue); pill(s,'RAG / CAG',3.72,2.25,1.2,C.green); pill(s,'MCP & Agents',5.15,2.25,1.5,C.orange); footer(s,n++); notes(s,'Opening question: Where have students already encountered AI today?');
//2
s=pptx.addSlide(); addBg(s); title(s,'Learning goals','By the end, students should be able to explain what AI systems do and use them responsibly.'); const goals=[['Define AI, Generative AI, and LLMs','Vocabulary for the rest of the unit'],['Explain how LLMs predict text','Tokens, patterns, training, and context'],['Use prompts and retrieval wisely','Prompt engineering, RAG, CAG'],['Understand tools and agents','MCP, function calls, Skills, workflows'],['Evaluate risks and ethics','Bias, hallucination, privacy, academic integrity']]; goals.forEach((g,i)=>{card(s,0.75+(i%3)*4.05,1.55+Math.floor(i/3)*2.05,3.55,1.45,{fill:i%2?'EFF6FF':'FFFFFF'}); bigNum(s,i+1,0.98+(i%3)*4.05,1.78+Math.floor(i/3)*2.05,[C.blue,C.purple,C.green,C.orange,C.pink][i]); s.addText(g[0],{x:1.68+(i%3)*4.05,y:1.72+Math.floor(i/3)*2.05,w:2.25,h:0.4,fontSize:17,bold:true,color:C.black,margin:0}); s.addText(g[1],{x:1.7+(i%3)*4.05,y:2.22+Math.floor(i/3)*2.05,w:2.2,h:0.36,fontSize:11.5,color:C.gray,margin:0});}); footer(s,n++); notes(s,'This slide previews the teaching path.');
//3
s=pptx.addSlide(); addBg(s,'ECFEFF'); title(s,'What is AI?','AI is software that performs tasks that usually require human intelligence.'); imgCrop(s,imgs.genai,7.1,1.0,5.7,5.5,0.15,0,0.7,1); bullet(s,['Recognizes patterns in data','Makes predictions or decisions','Learns from examples instead of fixed step-by-step rules','Can be narrow: one task, not a human mind'],0.75,1.55,5.6,2.6,{size:21}); s.addText('AI is not magic. It is math + data + computing power + human design.',{x:0.85,y:5.0,w:5.45,h:0.85,fontSize:22,bold:true,color:C.navy,fit:'shrink',margin:0}); footer(s,n++); notes(s,'Emphasize narrow AI: a calculator, chess engine, speech recognizer, and chatbot are very different tools.');
//4
s=pptx.addSlide(); addBg(s); title(s,'AI, Machine Learning, Deep Learning, Generative AI','These terms are related, but not the same.'); const rings=[['AI','Broad goal: machines doing intelligent tasks',0.85,1.6,11.6,4.8,C.navy],['Machine Learning','Learns patterns from data',1.75,2.2,9.8,3.55,C.blue],['Deep Learning','Uses many-layer neural networks',2.65,2.8,8.0,2.35,C.purple],['Generative AI','Creates new text, images, audio, code, or video',3.55,3.42,6.2,1.1,C.green]]; rings.forEach(r=>{s.addShape(pptx.ShapeType.roundRect,{x:r[2],y:r[3],w:r[4],h:r[5],rectRadius:0.25,fill:{color:r[6],transparency:85},line:{color:r[6],pt:2}}); s.addText(r[0],{x:r[2]+0.25,y:r[3]+0.18,w:2.9,h:0.32,fontSize:18,bold:true,color:r[6],margin:0}); s.addText(r[1],{x:r[2]+0.25,y:r[3]+0.55,w:4.4,h:0.3,fontSize:12,color:C.slate,margin:0});}); footer(s,n++); notes(s,'Use a nested category analogy: all sparrows are birds, but not all birds are sparrows.');
//5
s=pptx.addSlide(); addBg(s,C.navy); title(s,'What makes AI “generative”?','It produces new content rather than only classifying or predicting labels.'); imgCrop(s,imgs.genai,0.55,1.25,12.25,5.35); s.addShape(pptx.ShapeType.rect,{x:0.55,y:5.85,w:12.25,h:0.75,fill:{color:'000000',transparency:45},line:{transparency:100}}); s.addText('Generative AI learns patterns from examples, then creates new combinations that fit those patterns.',{x:1.0,y:6.08,w:11.2,h:0.25,fontSize:18,bold:true,color:C.white,align:'center',margin:0}); footer(s,n++); notes(s,'Examples: essay drafts, code, music, image generation, summarization, tutoring.');
//6
s=pptx.addSlide(); addBg(s); title(s,'Large Language Models: the core idea','An LLM is trained to predict likely next tokens from previous tokens.'); card(s,0.8,1.45,11.8,1.0,{fill:'F1F5F9'}); s.addText('The quick brown fox jumps over the ___',{x:1.15,y:1.75,w:11.1,h:0.35,fontSize:27,bold:true,color:C.black,align:'center',margin:0}); ['fence','moon','dog','log'].forEach((t,i)=>{card(s,1.4+i*2.8,3.0,2.1,0.75,{fill:['DBEAFE','F3E8FF','DCFCE7','FEF3C7'][i],lineTrans:70}); s.addText(t,{x:1.4+i*2.8,y:3.22,w:2.1,h:0.25,fontSize:19,bold:true,color:[C.blue,C.purple,C.green,C.orange][i],align:'center',margin:0});}); bullet(s,['A token can be a word, part of a word, punctuation, or code symbol','The model chooses among many possible next tokens','Long answers are built one token at a time'],1.2,4.7,11.0,1.4,{size:18}); footer(s,n++); notes(s,'Ask students to guess the blank, then explain that a model scores many possible completions.');
//7
s=pptx.addSlide(); addBg(s,'F8FAFC'); title(s,'Inside an LLM: tokens, embeddings, attention','LLMs turn words into numbers, compare context, then generate the next token.'); const steps=[['1','Tokenize','Split text into chunks'],['2','Embed','Convert tokens to vectors'],['3','Attend','Find important relationships'],['4','Generate','Predict and sample next token']]; steps.forEach((st,i)=>{connector(s,1.8+i*2.8,3.1,2.8+i*2.8,3.1,C.gray); card(s,0.75+i*3.0,2.0,2.35,2.0,{fill:['EFF6FF','F5F3FF','ECFDF5','FFF7ED'][i]}); bigNum(s,st[0],1.0+i*3.0,2.28,[C.blue,C.purple,C.green,C.orange][i]); s.addText(st[1],{x:1.7+i*3.0,y:2.33,w:1.05,h:0.25,fontSize:18,bold:true,color:C.black,margin:0}); s.addText(st[2],{x:1.03+i*3.0,y:3.12,w:1.85,h:0.55,fontSize:13,color:C.slate,align:'center',valign:'mid',margin:0});}); s.addText('Attention is like highlighting the words that matter most for the current prediction.',{x:1.2,y:5.2,w:10.9,h:0.65,fontSize:22,bold:true,color:C.navy,align:'center',margin:0}); footer(s,n++); notes(s,'The real math is more complex, but this is the right mental model.');
//8
s=pptx.addSlide(); addBg(s); title(s,'How models are trained','Training teaches the model patterns; alignment teaches it to be helpful and safer.'); const train=[['Data','Books, websites, code, images, examples'],['Pretraining','Predict missing or next tokens at huge scale'],['Fine-tuning','Practice following instructions and formats'],['Feedback & safety','Humans and automated checks guide behavior']]; train.forEach((st,i)=>{card(s,0.8,1.4+i*1.25,3.2,0.85,{fill:'FFFFFF'}); s.addText(st[0],{x:1.1,y:1.62+i*1.25,w:1.4,h:0.24,fontSize:16,bold:true,color:[C.blue,C.purple,C.green,C.orange][i],margin:0}); s.addText(st[1],{x:4.45,y:1.6+i*1.25,w:7.6,h:0.28,fontSize:16,color:C.slate,margin:0}); connector(s,4.0,1.82+i*1.25,4.35,1.82+i*1.25,[C.blue,C.purple,C.green,C.orange][i]);}); s.addText('Training requires many examples and lots of computing. It does not mean the model “understands” exactly like a person.',{x:0.9,y:6.55,w:11.4,h:0.35,fontSize:15,bold:true,color:C.gray,align:'center',margin:0}); footer(s,n++); notes(s,'Clarify: training is mostly before deployment. Chatting with a model usually does not immediately retrain it.');
//9
s=pptx.addSlide(); addBg(s,'F0F9FF'); title(s,'What can LLMs do well?','LLMs are especially useful when language, ideas, and structure matter.'); const uses=[['Tutor','Explain steps, ask questions, give hints'],['Writer','Brainstorm, outline, revise tone'],['Coder','Generate, explain, test, debug code'],['Analyst','Summarize, compare, extract patterns'],['Creative partner','Stories, games, images, music prompts'],['Translator','Convert between languages or reading levels']]; uses.forEach((u,i)=>{card(s,0.85+(i%3)*4.05,1.45+Math.floor(i/3)*2.05,3.55,1.45,{fill:['FFFFFF','EFF6FF','F5F3FF','ECFDF5','FFF7ED','FDF2F8'][i]}); s.addText(u[0],{x:1.1+(i%3)*4.05,y:1.74+Math.floor(i/3)*2.05,w:3.0,h:0.25,fontSize:18,bold:true,color:C.black,margin:0}); s.addText(u[1],{x:1.1+(i%3)*4.05,y:2.15+Math.floor(i/3)*2.05,w:2.95,h:0.38,fontSize:13,color:C.gray,fit:'shrink',margin:0});}); footer(s,n++); notes(s,'Invite students to add examples from their own classes.');
//10
s=pptx.addSlide(); addBg(s,'FFF7ED'); title(s,'Limits: why LLMs can be wrong','They predict plausible text, so they can sound confident even when facts are false.'); imgCrop(s,imgs.classroom,7.7,1.35,4.9,4.7,0.0,0,0.6,1); bullet(s,['Hallucination: invented facts, sources, or details','Bias: patterns from data can reflect society’s unfairness','Stale knowledge: training data can be out of date','No true memory unless a system gives it memory','Privacy risk: never paste secrets or personal data'],0.85,1.55,6.05,3.8,{size:20}); s.addText('Healthy habit: trust, but verify.',{x:0.9,y:5.85,w:6.3,h:0.45,fontSize:28,bold:true,color:C.orange,margin:0}); footer(s,n++); notes(s,'Show an example of a confident but false answer and ask how to check it.');
//11
s=pptx.addSlide(); addBg(s); title(s,'Prompt Engineering: how to ask better questions','A prompt is the instruction you give the AI. Better prompts make better outputs.'); const p=[['Role','“Act as a biology tutor…”'],['Task','“Explain photosynthesis…”'],['Context','“For a 9th-grade class…”'],['Constraints','“Use 5 bullets, no jargon…”'],['Examples','“Use this style: …”'],['Check','“Ask me 2 questions first.”']]; p.forEach((a,i)=>{card(s,0.8+(i%3)*4.1,1.35+Math.floor(i/3)*2.25,3.55,1.55,{fill:'FFFFFF'}); pill(s,a[0],1.05+(i%3)*4.1,1.62+Math.floor(i/3)*2.25,1.0,[C.blue,C.purple,C.green,C.orange,C.pink,C.cyan][i]); s.addText(a[1],{x:1.05+(i%3)*4.1,y:2.14+Math.floor(i/3)*2.25,w:2.95,h:0.4,fontSize:14,color:C.slate,fit:'shrink',margin:0});}); footer(s,n++); notes(s,'Ask students to improve a weak prompt: “Tell me about volcanoes.”');
//12
s=pptx.addSlide(); addBg(s,'F8FAFC'); title(s,'Prompt pattern: CLEAR','A simple checklist students can remember.'); const clear=[['C','Context','Who is the answer for?'],['L','Limits','Length, format, do/don’t'],['E','Examples','Show the desired style'],['A','Ask','State the task clearly'],['R','Review','Check facts and improve']]; clear.forEach((x,i)=>{card(s,0.85+i*2.45,2.0,2.05,2.55,{fill:['EFF6FF','F5F3FF','ECFDF5','FFF7ED','FDF2F8'][i]}); s.addText(x[0],{x:1.35+i*2.45,y:2.25,w:1.0,h:0.6,fontSize:40,bold:true,color:[C.blue,C.purple,C.green,C.orange,C.pink][i],align:'center',margin:0}); s.addText(x[1],{x:1.05+i*2.45,y:3.05,w:1.65,h:0.3,fontSize:16,bold:true,color:C.black,align:'center',margin:0}); s.addText(x[2],{x:1.08+i*2.45,y:3.55,w:1.58,h:0.42,fontSize:11.5,color:C.gray,align:'center',fit:'shrink',margin:0});}); s.addText('Weak: “Explain climate change.”  Strong: “Explain climate change to 10th graders in 6 bullets, include 1 analogy, and list 2 reliable sources to check.”',{x:0.9,y:5.55,w:11.55,h:0.7,fontSize:17,color:C.slate,align:'center',fit:'shrink',margin:0}); footer(s,n++); notes(s,'Have students write one CLEAR prompt for a topic they are studying.');
//13
s=pptx.addSlide(); addBg(s,C.navy); title(s,'RAG: Retrieval-Augmented Generation','RAG lets an AI look up relevant information before answering.'); imgCrop(s,imgs.rag,0.8,1.25,11.8,5.6); s.addShape(pptx.ShapeType.rect,{x:0.8,y:6.2,w:11.8,h:0.45,fill:{color:'000000',transparency:40},line:{transparency:100}}); s.addText('Question → Search documents → Add evidence to prompt → Generate answer with sources',{x:1.1,y:6.31,w:11.1,h:0.18,fontSize:15,bold:true,color:C.white,align:'center',margin:0}); footer(s,n++); notes(s,'RAG is like an open-book answer: the model still writes, but it has relevant pages in front of it.');
//14
s=pptx.addSlide(); addBg(s); title(s,'RAG pipeline: one practical view','A school chatbot could answer from class notes, a textbook, and teacher policies.'); const ragSteps=[['Upload content','PDFs, websites, notes'],['Chunk & embed','Turn passages into searchable vectors'],['Retrieve','Find the most relevant chunks'],['Generate','Answer using retrieved context'],['Cite & verify','Show sources and let humans check']]; ragSteps.forEach((st,i)=>{if(i<4) connector(s,2.55+i*2.2,3.45,3.0+i*2.2,3.45,[C.blue,C.purple,C.green,C.orange][i]); card(s,0.7+i*2.45,2.2,2.05,2.4,{fill:['EFF6FF','F5F3FF','ECFDF5','FFF7ED','FDF2F8'][i]}); s.addText(st[0],{x:0.92+i*2.45,y:2.62,w:1.6,h:0.35,fontSize:15,bold:true,color:C.black,align:'center',fit:'shrink',margin:0}); s.addText(st[1],{x:0.9+i*2.45,y:3.35,w:1.65,h:0.55,fontSize:11.5,color:C.gray,align:'center',fit:'shrink',margin:0});}); s.addText('RAG is useful when knowledge changes often or is too large to fit in the prompt.',{x:0.95,y:5.55,w:11.2,h:0.35,fontSize:18,bold:true,color:C.navy,align:'center',margin:0}); footer(s,n++); notes(s,'Mention examples: school handbook assistant, science lab safety assistant, library research assistant.');
//15
s=pptx.addSlide(); addBg(s,'F8FAFC'); title(s,'CAG: Cache-Augmented Generation','CAG preloads stable knowledge and reuses cached context for faster answers.'); card(s,0.85,1.5,5.45,4.45,{fill:'EFF6FF'}); s.addText('RAG',{x:3.05,y:1.85,w:1.1,h:0.35,fontSize:24,bold:true,color:C.blue,align:'center',margin:0}); bullet(s,['Searches at question time','Good for large or changing collections','Can cite retrieved passages','More moving parts and possible retrieval mistakes'],1.15,2.45,4.85,2.55,{size:16}); card(s,7.0,1.5,5.45,4.45,{fill:'ECFDF5'}); s.addText('CAG',{x:9.2,y:1.85,w:1.1,h:0.35,fontSize:24,bold:true,color:C.green,align:'center',margin:0}); bullet(s,['Loads a limited knowledge base ahead of time','Reuses a key-value cache','Good for small, stable manuals or policies','Faster, but limited by context size'],7.3,2.45,4.85,2.55,{size:16}); footer(s,n++); notes(s,'CAG is newer and terminology varies. Here it refers to Cache-Augmented Generation.');
//16
s=pptx.addSlide(); addBg(s); title(s,'MCP: Model Context Protocol','MCP is a common way for AI apps to connect with tools and data sources.'); imgCrop(s,imgs.agents,7.0,1.2,5.55,5.35,0.2,0,0.75,1); bullet(s,['Think of MCP like a universal adapter','It lets models access files, databases, apps, and tools through standardized servers','It helps developers avoid custom one-off connectors for every tool','Students should understand the idea: AI + approved tools + permissions'],0.8,1.55,5.75,3.6,{size:19}); s.addText('Key idea: the model does not “know everything” — connected systems provide context when allowed.',{x:0.85,y:5.65,w:5.95,h:0.55,fontSize:18,bold:true,color:C.navy,fit:'shrink',margin:0}); footer(s,n++); notes(s,'Avoid deep protocol details. Focus on the adapter metaphor and permissions.');
//17
s=pptx.addSlide(); addBg(s,'F8FAFC'); title(s,'Agents and Agent Skills','Agents are AI systems that can plan, use tools, and complete multi-step tasks.'); const agent=[['Goal','What needs to be done?'],['Plan','Break the task into steps'],['Tools','Search, code, calendar, email, files'],['Memory/context','Keep relevant state'],['Review','Check results and ask for approval']]; agent.forEach((a,i)=>{if(i<4) connector(s,2.65+i*2.25,3.35,3.0+i*2.25,3.35,C.gray); card(s,0.75+i*2.45,2.1,2.05,2.25,{fill:'FFFFFF'}); s.addText(a[0],{x:1.02+i*2.45,y:2.55,w:1.5,h:0.24,fontSize:15,bold:true,color:[C.blue,C.purple,C.green,C.orange,C.pink][i],align:'center',margin:0}); s.addText(a[1],{x:0.95+i*2.45,y:3.1,w:1.65,h:0.45,fontSize:11.5,color:C.gray,align:'center',fit:'shrink',margin:0});}); bullet(s,['Skills are reusable capabilities an agent can call, like making slides or analyzing spreadsheets','Strong agents need guardrails: permissions, logging, human review, and limits'],1.2,5.35,10.8,0.85,{size:17}); footer(s,n++); notes(s,'Examples: a research agent, coding agent, study-planner agent. Emphasize human control.');
//18
s=pptx.addSlide(); addBg(s); title(s,'Responsible use in school','AI can support learning, but it should not replace thinking.'); const rules=[['Use AI as a tutor','Ask for hints, examples, and feedback'],['Show your thinking','Explain what you did and what AI helped with'],['Verify facts','Check sources, calculations, and citations'],['Protect privacy','Do not upload personal, private, or school-restricted data'],['Follow class rules','Different assignments allow different levels of AI help']]; rules.forEach((r,i)=>{card(s,0.85+(i%2)*6.1,1.3+Math.floor(i/2)*1.65,5.45,1.1,{fill:['EFF6FF','F5F3FF','ECFDF5','FFF7ED','FDF2F8'][i]}); s.addText(r[0],{x:1.1+(i%2)*6.1,y:1.55+Math.floor(i/2)*1.65,w:2.4,h:0.25,fontSize:16,bold:true,color:C.black,margin:0}); s.addText(r[1],{x:3.55+(i%2)*6.1,y:1.56+Math.floor(i/2)*1.65,w:2.4,h:0.32,fontSize:12.3,color:C.gray,fit:'shrink',margin:0});}); footer(s,n++); notes(s,'This can become a classroom AI use policy discussion.');
//19
s=pptx.addSlide(); addBg(s,'ECFEFF'); title(s,'Class activity: build a mini RAG answer','Students practice asking, retrieving, answering, and checking.'); const acts=[['1. Question','Choose a class topic question'],['2. Evidence','Find two trustworthy passages'],['3. Prompt','Ask AI to answer only from the passages'],['4. Check','Mark every claim as supported or unsupported'],['5. Reflect','What did AI help with? What still needed humans?']]; acts.forEach((a,i)=>{card(s,0.9,1.35+i*1.05,11.5,0.72,{fill:'FFFFFF'}); s.addText(a[0],{x:1.2,y:1.55+i*1.05,w:2.0,h:0.2,fontSize:15,bold:true,color:[C.blue,C.purple,C.green,C.orange,C.pink][i],margin:0}); s.addText(a[1],{x:3.3,y:1.55+i*1.05,w:7.6,h:0.2,fontSize:14,color:C.slate,margin:0});}); footer(s,n++); notes(s,'This activity can be done with printed passages, no paid tools required.');
//20
s=pptx.addSlide(); addBg(s,C.navy); title(s,'Key takeaways','AI is powerful, but students should learn how it works and how to use it responsibly.'); bullet(s,['LLMs generate by predicting tokens using patterns learned from data','Generative AI can create text, images, code, audio, and more','Prompt engineering improves instructions and outputs','RAG adds external evidence; CAG caches stable knowledge for speed','MCP and agents connect models to tools, but need permissions and guardrails','Best practice: use AI to learn, then verify and explain'],0.9,1.45,7.4,3.95,{size:19,color:'E2E8F0'}); imgCrop(s,imgs.classroom,8.75,1.25,3.9,4.6,0.2,0.08,0.55,0.85); s.addText('Think first. Ask well. Check carefully.',{x:0.95,y:5.95,w:7.6,h:0.45,fontSize:28,bold:true,color:C.yellow,margin:0}); footer(s,n++); notes(s,'End with student questions and a reminder that AI literacy is a practical skill.');
//21 sources
s=pptx.addSlide(); addBg(s); title(s,'Sources and further reading','Teacher reference links used to prepare this deck.'); const src=['OpenAI Developers: Agents SDK and tool orchestration examples','Microsoft Learn: Prompt engineering concepts','Model Context Protocol official documentation','Anthropic: Introducing the Model Context Protocol','IBM Developer: Optimizing LLMs with cache augmented generation','Chan et al. (2024): Don\'t Do RAG: When Cache-Augmented Generation is All You Need']; bullet(s,src,0.85,1.45,11.6,3.8,{size:17}); s.addText('Suggested teacher note: ask students to compare AI output with at least two reliable sources when facts matter.',{x:0.9,y:6.0,w:11.3,h:0.5,fontSize:17,bold:true,color:C.navy,align:'center',margin:0}); footer(s,n++); notes(s,'These sources are for teacher preparation. Add local school policy before using AI in class.');

for (const sl of pptx._slides) {
  warnIfSlideHasOverlaps(sl, pptx, { muteContainment: true, ignoreLines: true, ignoreDecorativeShapes: true });
  warnIfSlideElementsOutOfBounds(sl, pptx);
}

pptx.writeFile({ fileName: '/mnt/data/AI_LLMs_Generative_AI_High_School_Teaching_Deck.pptx' });
EOF
node /mnt/data/create_ai_llm_deck.js